name: Generate Repo Metrics
on:
  # Runs automatically at midnight every day
  schedule: [{cron: "0 0 * * *"}]
  # Allows you to manually trigger it from the Actions tab anytime
  workflow_dispatch:
  # Runs whenever you push changes to the main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Repository Infographics
        uses: lowlighter/metrics@latest
        with:
          # Your secret token created in Step 2
          token: ${{ secrets.METRICS_TOKEN }}

          # Target repository specifics
          user: NishantSaud
          repo: Nepali-Tool-Kit
          output_action: commit
          committer_branch: main
          filename: github-metrics.svg

          # Layout & Template settings
          template: repository
          base: header, metadata

          # Plugin: Showcase Contributors details
          plugin_contributors: yes
          plugin_contributors_base: ""
          plugin_contributors_head: ""
          plugin_contributors_ignored: github-actions[bot], dependabot[bot]
          plugin_contributors_contributions: yes

          # Plugin: Showcase Total Lines of Code Changed
          plugin_lines: yes

          # Plugin: Showcase Follow-up analytics (PRs and Issues tracking)
          plugin_followup: yes
          plugin_followup_sections: repositories